In [ ]:
## 

In [19]:
import numpy as np
a = np.array([1,2,3,4,5])

In [20]:
print(a)

[1 2 3 4 5]


In [8]:
zroner = np.zeros((3,3))
print(zroner)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
meker = np.ones((2,7))
print(meker)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [11]:
datark = np.empty((3,3))
print(datark)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
lcon = np.full((3,4),17)
print(lcon)

[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


## boolean expressions 

In [22]:
print([i for i in a if i >= 4 ])

[4, 5]


In [25]:
a[[True,True,True,False,False]]

array([1, 2, 3])

In [27]:
a >= 5

array([False, False, False, False,  True])

In [28]:
a[a >= 4]

array([4, 5])

In [29]:
import numpy as np

# Example 2D array
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 1, 8]])

# Select rows where the second column is less than 3
result = two_dim_array[two_dim_array[:, 1] < 3]
print(result)


[[1 2 3]
 [7 1 8]]


In [30]:
import numpy as np

# Example 2D array
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 1, 8]])

# Select rows where the second column is less than 3
result = two_dim_array[two_dim_array[:, 1] < 3,1]
print(result)


[2 1]


In [43]:
b = np.arange(1,16)

In [47]:
b.size

15

In [48]:
b.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [49]:
b.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [50]:
b.reshape(3,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
b.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
b.reshape(4,-1)

ValueError: cannot reshape array of size 15 into shape (4,newaxis)

In [54]:
transposted_b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
b = b.reshape(3,-1)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
transposted_b = b.T
transposted_b

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [24]:
import numpy as np
import time 


In [25]:
start_time = time.time()
py_list = list(range(10**7))
py_sum = sum(py_list)
end_time = time.time()
exec_time1 = end_time - start_time 
print(exec_time)

-0.01826930046081543


In [26]:
start_time = time.time()
num_list = np.arange(10**7)
sum_list = np.sum(num_list)
end_time = time.time()
exec_time2 = start_time - end_time 

In [27]:
print(exec_time)

-0.01826930046081543


In [28]:
exec_time1/exec_time2

-8.305546032066148

In [29]:
start_time = time.time()
py_list = list(range(10**7))
py_sum = sum(py_list)
end_time = time.time()
exec_time1 = end_time - start_time 
print(exec_time)

-0.01826930046081543


In [16]:
# Creating empty array
empty = np.empty((2,2)) # պատահական արժեքներ

# Creating array with a constant value
full = np.full((2,3), 7)

print(empty)
print(full)

[[0. 0.]
 [0. 0.]]
[[7 7 7]
 [7 7 7]]


In [18]:
data = np.array([1,2,3])
data[-2:]

array([2, 3])

In [19]:
two_dim_array = np.array([[1, 2, 3, 4, 5],
                          [6, 7, 8, 9, 10],
                          [11, 12, 13, 14, 15],
                          [16, 17, 18, 19, 20],
                          [21, 22, 23, 24, 25]])

print("\nOriginal 2D array:")
print(two_dim_array)


Original 2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
np.array([1,2,3,4], dtype="str")

array(['1', '2', '3', '4'], dtype='<U1')

In [35]:
a=np.array([1,2,3,4],dtype ="int32" )

In [36]:
a.dtype


dtype('int32')

In [37]:
# Using NumPy arrays
start_time = time.time()

np_array = np.arange(10**8)  # Create a NumPy array with 100 million elements
np_sum = np.sum(np_array)  # Calculate the sum of the array

end_time = time.time()
execution_time_np = end_time - start_time
print("NumPy execution time:", execution_time_np)

NumPy execution time: 0.1763291358947754


In [38]:
# Using Python lists
start_time = time.time()

py_list = list(range(10**8))  # Create a Python list with 10 million elements
py_sum = sum(py_list)  # Calculate the sum of the list

end_time = time.time()

execution_time_py = end_time - start_time
print("Python list execution time:", execution_time_py)

Python list execution time: 2.480778932571411


In [39]:
print(f"NumPy was {execution_time_py / execution_time_np:.2f}x faster, հզոր NumPy")

NumPy was 14.07x faster, հզոր NumPy
